### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by nick-telsan** [nick-telsan/tasc#13]
## Tasks
- [ ] User can create tasks
  - [ ] User can specify due date and if the task repeats
  - [ ] Database can generate instances of tasks based on repeats
- [ ] User can mark tasks as complete

## Habits
- [ ] User can create habits
  - [ ] User can specify if the habit is a negative/positive habit or a custom input
- [ ] User can record habits
  - [ ] For negative/positive, record direction of input
  - [ ] For custom, record custom input as string
- [ ] (Stretch) User can see results of their habits
- [ ] (Stretchier) User can see a graph of their habits

## Other
- [ ] User can choose whether they want to see completed tasks

## Distribution
- [ ] Build and distribute
