### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by nick-telsan** [nick-telsan/tasc#5]
## Tasks

- [ ] User can create multiple tasks
- [ ] Tasks default to an incomplete status and can be completed
- [ ] Tasks start off with a white / grey color and move to red the longer they are not done.
- [ ] Tasks can have due dates
- [ ] Tasks can comments
- [ ] Tasks can have subtasks

Probably more
